# Theme metadata
name = "nord" # Based on https://www.nordtheme.com/

[light]
  # Primary
  primary = "#069465"
  background = "#f2faf7"

  link = "#069465"
  link_hover = "#046344"

  # Menu
  menu_primary = "#0fbf85"
  menu_text = "#f2faf7"
  menu_text_active = "#046344"
  menu_title = "#069465"

  # Home sections
  home_section_odd = "#f2faf7"
  home_section_even = "##cfe8de"